export const urlToNameMapping = {
    "/login": "로그인",
    "/signup": "회원가입",
    "/admin/member": "관리자 - 회원 관리",
    "/admin/edu": "관리자 - 교육 관리",
    "/admin/eduHist": "관리자 - 교육 신청 관리",
    "/admin/rentHist": "관리자 - 대관 신청 관리",
    "/admin/ftmain": "관리자- 여성인재풀 - 메인",
    "/admin/pay": "관리자 - 결제 내역",
    "/admin/org": "관리자 - 유관 기관",
    "/admin/board": "관리자 - 게시판 관리",
    "/admin/log": "관리자 - 로그",
    "/edu/calendar": "관리자 - 교육 일정",
    "/edu/list": "관리자 - 교육 신청",
    "/edu/applylist": "관리자 - 교육 신청내역",
    "/ftmain": "여성인재풀",
    "/ftw/new": "여성인재풀 등록 신청 ",
    "/admin/ftmain/ftw": "관리자 - 여성인재풀 - 등록 리스트 ",
    "/admin/ftmain/ftc": "관리자 - 여성인재풀 - 등록 리스트 ",
};