export const urlToNameMapping = {
    "/": "메인 페이지",
    "/login": "로그인 페이지",
    "/signUp": "회원 가입 페이지",
    "/search": "검색 페이지",

    "/admin/member": "관리자 - 회원 관리",
    "/admin/edu": "관리자 - 교육 리스트",
    "/admin/edu/add": "관리자 - 교육 추가",
    "/admin/edu/edit/:eduNum": "관리자 - 교육 편집",
    "/admin/eduHist": "관리자 - 교육 신청 내역",
    "/admin/rentHist": "관리자 - 대관 신청 내역",
    "/admin/org": "관리자 - 유관기관",
    "/admin/board": "관리자 - 게시판 관리",
    "/admin/board/post/:boardNum": "관리자 - 게시글 관리",
    "/admin/log": "관리자 - 로그 리스트",
    "/admin/pay": "관리자 - 결제 리스트",
    "admin/ftmain": "관리자 - FT 메인 페이지",
    "admin/ftmain/ftw/:id": "관리자 - FTW 상세 페이지",

    "/edu/calendar": "교육 캘린더 페이지",
    "/edu/list": "교육 리스트 페이지",
    "/edu/list/detail/:eduNum": "교육 상세 페이지",
    "/edu/list/apply/:eduNum": "교육 신청 페이지",
    "/edu/applylist": "교육 신청 리스트 페이지",

    "/pay/:rentHistNum/:fee": "결제 페이지",

    "/sj": "SJ 뉴스 페이지",
    "/posts": "게시글 리스트 페이지",
    "/post/detail/:boardNum/:postNum": "게시글 상세 페이지",
    "/imgpost/3": "세종시 기관 및 단체 소식",
    "/post/:boardNum": "공지사항 페이지",
    "/csl/:boardNum": "노동 목록 페이지",
    "/error": "에러 페이지",
    "/post/new": "새로운 게시글 페이지",

    "/rent/process": "대관 과정 페이지",
    "/rent/status": "대관 상태 페이지",
    "/rent/apply": "대관 신청 페이지",
    "/rent/review": "대관 리뷰 페이지",

    "/mypage/edu": "내 교육 페이지",
    "/mypage/rent": "내 대관 페이지",
    "/mypage/active": "내 활동 페이지",
    "/mypage/ftw": "내 여성 페이지",
    "/mypage/club": "내 소모임 페이지",
    "/mypage/csl": "내 상담 페이지",
    "/mypage/infoEdit": "내 정보 편집 페이지",
    "/mypage/infoEditSuccess": "내 정보 수정 완료 페이지",

    "/clubs": "소모임 페이지",
    "/clubs/new": "새로운 소모임 페이지",
    "/clubs/:id": "소모임 상세 페이지",
    "/clubs/edit/:id": "소모임 편집 페이지",

    "/ftmain": "인재풀 메인 페이지",
    "/ftw/new": "여성 정보 추가 페이지",
    "/ftw/dtl/:id": "여성 상세 페이지",
    "/ftw/edit/:id": "여성 편집 페이지",
    "/ftc/new": "FTC 신규 페이지",
    "/ftc/dtl/:id": "FTC 상세 페이지",
    "/ftc/edit/:id": "FTC 편집 페이지",
    "/ftmpop/:ftcNum": "매칭 팝업 페이지",

    "/sms": "SMS 페이지",

    "/chat": "채팅 페이지",
    "/chat/:memNum": "개별 채팅 페이지",
    "/chattest": "채팅 테스트 페이지"
}